[5주차] 댓글 알림 API
GDSC-SWU/2022-02-Web-Dev-Toy-Project-BE pull request #41
Opened 2023-01-30 08:01 UTC by Skyminn

-  #37

2023-01-30 09:01 UTC, Queue-ri requested changes

2023-01-30 09:01 UTC, Queue-ri commented on prisma/migrations/20230130075417_create_categories/migration.sql
> +ALTER TABLE `Posts` ADD COLUMN `postStatus` VARCHAR(20) NOT NULL;
Alter문이 나오지 않게끔 sql 폴더 삭제하고 다시 생성해서 커밋해주세요. migration시 DB가 초기화되어도 괜찮습니다. 수정하시면 squash merge 할게요

2023-01-30 10:49 UTC, Skyminn commented on prisma/migrations/20230130075417_create_categories/migration.sql
> +ALTER TABLE `Posts` ADD COLUMN `postStatus` VARCHAR(20) NOT NULL;
수정했습니다.

2023-02-01 15:26 UTC, chaeeun-Han approved these changes

2023-02-01 15:26 UTC, jiyunBae007 approved these changes

2023-02-01 15:37 UTC, Park-HyeJeong approved these changes

2023-02-02 02:15 UTC, Queue-ri approved these changes

2023-02-02 02:32 UTC, merged